// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Naorobi.Api.Data;

#nullable disable

namespace Naorobi.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260409171238_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Naorobi.Api.Models.Admin", b =>
                {
                    b.Property<int>("Id_Admin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Admin");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Naorobi.Api.Models.Carro", b =>
                {
                    b.Property<int>("Id_Carro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Caballos_Fuerza")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_Admin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Maxima_Velocidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Precio_Renta_Diario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo_Combustible")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo_Motor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Transmision")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Carro");

                    b.HasIndex("Id_Admin");

                    b.ToTable("Carros");
                });

            modelBuilder.Entity("Naorobi.Api.Models.Reserva", b =>
                {
                    b.Property<int>("Id_Reserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha_Final")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha_Inicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id_Carro")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id_Reserva");

                    b.HasIndex("Id_Carro");

                    b.HasIndex("Id_Usuario");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Naorobi.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Usuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Naorobi.Api.Models.Carro", b =>
                {
                    b.HasOne("Naorobi.Api.Models.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("Id_Admin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Naorobi.Api.Models.Reserva", b =>
                {
                    b.HasOne("Naorobi.Api.Models.Carro", "Carro")
                        .WithMany()
                        .HasForeignKey("Id_Carro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Naorobi.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carro");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
